# Generated by Django 5.1.7 on 2025-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('bio', models.TextField()),
                ('idade', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
