# Generated by Django 5.1.7 on 2025-03-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
