# Generated by Django 5.1.7 on 2025-03-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contatos.categoria'),
            preserve_default=False,
        ),
    ]
